import { permissionWords } from './permissions';

/** Every user-facing string. Plain and warm; never game words or exclamation marks (CLAUDE.md rule 11). */
export const words = {
  documentary: {
    defaultTitle: 'My documentary',
  },
  permissions: permissionWords,
  today: {
    placeholderTitle: 'Life Documentary',
    placeholderLine: 'Your first question arrives soon.',
    modeLabel: 'Record with',
    modeVideo: 'Video',
    modeVoice: 'Voice',
    holdLonger: 'Hold a little longer to keep an answer.',
    secondsLeft: 'seconds left',
    startRecording: 'Start recording',
    stopRecording: 'Stop recording',
    openSettings: 'Open Settings',
    couldNotSave: 'This one could not be saved. Try once more.',
  },
  extras: {
    photo: 'Photo',
    fromLibrary: 'From library',
    note: 'Note',
    place: 'Place',
    noteLabel: 'A line about today',
    save: 'Save',
    close: 'Close',
    clipTooLong: 'Clips from the library can be up to a minute long. This one is longer.',
    clipUnreadable: 'This clip could not be read. Try another one.',
    moodLabel: 'Mood',
    placeLabel: 'Add the place',
    placeUse: 'Use this place',
    placeNotFound: 'No place name was found here.',
    keepOnPhone: 'Keep on this phone',
    keepOnPhoneHelp: 'This moment stays on this phone and is never used in episodes.',
    saved: 'Saved',
    takePhoto: 'Take photo',
    flip: 'Flip',
    cancel: 'Cancel',
  },
  moods: {
    bright: 'Bright',
    calm: 'Calm',
    tender: 'Tender',
    tired: 'Tired',
    heavy: 'Heavy',
  },
  tags: {
    tag: 'Tag',
    trayLabel: 'Tag this moment',
    storylines: 'Storylines',
    cast: 'Cast',
    newStoryline: 'New storyline',
    namePerson: 'Name a person',
    addStoryline: 'Add storyline',
    addPerson: 'Add person',
    done: 'Done',
    titleEmpty: 'Give the storyline a name.',
    titleTooLong: 'A storyline name can be up to 60 characters.',
    titleTaken: 'An open storyline already has this name.',
    nameInvalid: 'A name can be 1 to 40 characters.',
    relationInvalid: 'A relation can be up to 40 characters.',
    tooManyStorylines: 'A moment can hold up to 10 storylines.',
    tooManyCast: 'A moment can hold up to 20 people.',
    unavailable: 'Something here is no longer available. Try once more.',
  },
  lab: {
    title: 'Design lab',
    replay: 'Play again',
    reducedMotionOn: 'Reduced motion is on',
  },
  button: {
    holdToAnswer: 'Hold to answer',
    recording: 'Recording',
    saved: 'Saved',
  },
} as const;

export const bannedWords = ['streak', 'badge', 'level up', 'leaderboard', 'points', 'xp'] as const;
export * from './recap';
