import { permissionWords } from './permissions';
import { monthAndYear } from './recap';

/** Every user-facing string. Plain and warm; never game words or exclamation marks (CLAUDE.md rule 11). */
export const words = {
  documentary: {
    defaultTitle: 'My documentary',
  },
  permissions: permissionWords,
  today: {
    placeholderTitle: 'Life Documentary',
    placeholderLine: 'Your first question arrives soon.',
    modeLabel: 'Record with',
    modeVideo: 'Video',
    modeVoice: 'Voice',
    holdLonger: 'Hold a little longer to keep an answer.',
    secondsLeft: 'seconds left',
    startRecording: 'Start recording',
    stopRecording: 'Stop recording',
    openSettings: 'Open Settings',
    couldNotSave: 'This one could not be saved. Try once more.',
  },
  extras: {
    photo: 'Photo',
    fromLibrary: 'From library',
    note: 'Note',
    place: 'Place',
    noteLabel: 'A line about today',
    save: 'Save',
    close: 'Close',
    clipTooLong: 'Clips from the library can be up to a minute long. This one is longer.',
    clipUnreadable: 'This clip could not be read. Try another one.',
    moodLabel: 'Mood',
    placeLabel: 'Add the place',
    placeUse: 'Use this place',
    placeNotFound: 'No place name was found here.',
    keepOnPhone: 'Keep on this phone',
    keepOnPhoneHelp: 'This moment stays on this phone and is never used in episodes.',
    saved: 'Saved',
    takePhoto: 'Take photo',
    flip: 'Flip',
    cancel: 'Cancel',
  },
  moods: {
    bright: 'Bright',
    calm: 'Calm',
    tender: 'Tender',
    tired: 'Tired',
    heavy: 'Heavy',
  },
  tags: {
    tag: 'Tag',
    trayLabel: 'Tag this moment',
    storylines: 'Storylines',
    cast: 'Cast',
    newStoryline: 'New storyline',
    namePerson: 'Name a person',
    addStoryline: 'Add storyline',
    addPerson: 'Add person',
    done: 'Done',
    titleEmpty: 'Give the storyline a name.',
    titleTooLong: 'A storyline name can be up to 60 characters.',
    titleTaken: 'An open storyline already has this name.',
    nameInvalid: 'A name can be 1 to 40 characters.',
    relationInvalid: 'A relation can be up to 40 characters.',
    tooManyStorylines: 'A moment can hold up to 10 storylines.',
    tooManyCast: 'A moment can hold up to 20 people.',
    unavailable: 'Something here is no longer available. Try once more.',
  },
  nav: {
    today: 'Today',
    storylines: 'Storylines',
    cast: 'Cast',
    settings: 'Settings',
  },
  storylines: {
    title: 'Storylines',
    since: (openedOn: string) => `since ${monthAndYear(openedOn)}`,
    moments: (n: number) => (n === 1 ? '1 moment' : `${n} moments`),
    closed: 'Closed',
    newStoryline: 'New storyline',
    titleLabel: 'Name',
    save: 'Save',
    rename: 'Rename',
    close: 'Close storyline',
    reopen: 'Reopen',
    remove: 'Remove',
    removeAsk: 'Remove this storyline? The moments tagged with it stay in your documentary.',
    removeConfirm: 'Remove it',
    keep: 'Keep it',
    empty:
      'A storyline is a thread of your life you want to follow for a while, like the new job or training for the half marathon.',
  },
  cast: {
    title: 'Cast',
    namePerson: 'Name a person',
    nameLabel: 'Name',
    relationLabel: 'Relation, if you like',
    save: 'Save',
    rename: 'Rename',
    saveRelation: 'Save relation',
    remove: 'Remove',
    removeAsk: 'Remove this person? The moments with them stay; only the name is taken off.',
    removeConfirm: 'Remove them',
    keep: 'Keep them',
    empty:
      "Name the people in your days. Names stay on this phone, and nobody's face or voice is ever recognised.",
  },
  reminders: {
    notificationTitle: "Today's question",
    notificationBody: 'One question, ten seconds.',
    channelName: 'Daily question',
    settingsTitle: 'Settings',
    dailyQuestion: 'Daily question',
    dailyQuestionHelp: 'One quiet reminder a day, at the time you choose.',
    time: 'Time',
    hour: 'Hour',
    minutes: 'Minutes',
    earlier: 'Earlier',
    later: 'Later',
    denied: 'Notifications are off for Life Documentary. You can turn them on in Settings.',
    offerLine: "Would a quiet reminder help? One a day, for the day's question.",
    offerAccept: 'Remind me each morning',
    offerDismiss: 'Not now',
  },
  lab: {
    title: 'Design lab',
    replay: 'Play again',
    reducedMotionOn: 'Reduced motion is on',
  },
  button: {
    holdToAnswer: 'Hold to answer',
    recording: 'Recording',
    saved: 'Saved',
  },
} as const;

export const bannedWords = ['streak', 'badge', 'level up', 'leaderboard', 'points', 'xp'] as const;
export * from './recap';
