import type { QuestionTemplate } from '@life/contracts';

/**
 * The daily question bank (P7). One question per template, answered out loud in about ten seconds.
 * Slot templates ({storyline}, {person}, {place}) carry only their slot's tag. The engine fills slots
 * with names the person typed; it never infers anything about them.
 */
// One template per line so the bank reads as a list.
// prettier-ignore
export const questionTemplates: readonly QuestionTemplate[] = [
  { id: 'q001', tags: ['open_storyline'], text: 'Where are things with {storyline} this week?' },
  { id: 'q002', tags: ['open_storyline'], text: 'What happened next with {storyline}?' },
  { id: 'q003', tags: ['open_storyline'], text: "What's one step you took on {storyline} today?" },
  { id: 'q004', tags: ['open_storyline'], text: 'Who else is part of {storyline} right now?' },
  { id: 'q005', tags: ['open_storyline'], text: 'What surprised you about {storyline} lately?' },
  { id: 'q006', tags: ['open_storyline'], text: "What's one scene from {storyline} today?" },
  { id: 'q007', tags: ['open_storyline'], text: "What's the hardest part of {storyline} at the moment?" },
  { id: 'q008', tags: ['open_storyline'], text: 'What would you like to remember about {storyline} from this week?' },
  { id: 'q009', tags: ['open_storyline'], text: "What's changed with {storyline} since you last talked about it?" },
  { id: 'q010', tags: ['open_storyline'], text: 'What are you waiting on with {storyline}?' },
  { id: 'q011', tags: ['open_storyline'], text: 'How does {storyline} feel today compared with when it started?' },
  { id: 'q012', tags: ['open_storyline'], text: 'What did you learn from {storyline} this week?' },
  { id: 'q013', tags: ['open_storyline'], text: "What's going well with {storyline}?" },
  { id: 'q014', tags: ['open_storyline'], text: "What's one detail about {storyline} you don't want to forget?" },
  { id: 'q015', tags: ['open_storyline'], text: 'Where were you when you last thought about {storyline}?' },
  { id: 'q016', tags: ['open_storyline'], text: 'What would you tell a friend about {storyline} today?' },
  { id: 'q017', tags: ['open_storyline'], text: 'What needs to happen next with {storyline}?' },
  { id: 'q018', tags: ['open_storyline'], text: 'What did you see or hear today that made you think of {storyline}?' },
  { id: 'q019', tags: ['open_storyline'], text: 'Who helped with {storyline} recently?' },
  { id: 'q020', tags: ['open_storyline'], text: 'What made you smile about {storyline} this week?' },
  { id: 'q021', tags: ['open_storyline'], text: "What's still up in the air with {storyline}?" },
  { id: 'q022', tags: ['open_storyline'], text: 'What part did {storyline} play in your day?' },
  { id: 'q023', tags: ['after_quiet_days'], text: "It's been a quiet few days. What's one small thing from today?" },
  { id: 'q024', tags: ['after_quiet_days'], text: 'How have your days been lately, busy or slow?' },
  { id: 'q025', tags: ['after_quiet_days'], text: "What's something ordinary from today you'd like to keep?" },
  { id: 'q026', tags: ['after_quiet_days'], text: 'When did things slow down today?' },
  { id: 'q027', tags: ['after_quiet_days'], text: "What's one thing you did for yourself today?" },
  { id: 'q028', tags: ['after_quiet_days'], text: 'What was the first thing you noticed when you woke up today?' },
  { id: 'q029', tags: ['after_quiet_days'], text: 'What have you been enjoying this week?' },
  { id: 'q030', tags: ['after_quiet_days'], text: "What's on your mind as the day winds down?" },
  { id: 'q031', tags: ['after_quiet_days'], text: 'What did you eat today that you liked?' },
  { id: 'q032', tags: ['after_quiet_days'], text: 'Where did you spend most of today?' },
  { id: 'q033', tags: ['after_quiet_days'], text: "What's one sound you heard today?" },
  { id: 'q034', tags: ['after_quiet_days'], text: 'What small thing went right today?' },
  { id: 'q035', tags: ['after_quiet_days'], text: 'What are you hoping for tomorrow?' },
  { id: 'q036', tags: ['anniversary'], text: "A year ago today you recorded a moment. What's different now?" },
  { id: 'q037', tags: ['anniversary'], text: "What's changed in your life since this time last year?" },
  { id: 'q038', tags: ['anniversary'], text: 'If you could talk to yourself a year ago, what would you say?' },
  { id: 'q039', tags: ['anniversary'], text: 'A year on, who do you spend most of your time with?' },
  { id: 'q040', tags: ['anniversary'], text: "What's something you do now that you didn't do a year ago?" },
  { id: 'q041', tags: ['anniversary'], text: "What's something from the past year you're proud of?" },
  { id: 'q042', tags: ['anniversary'], text: 'What from a year ago is still part of your life today?' },
  { id: 'q043', tags: ['anniversary'], text: 'One year on, what does an ordinary day look like for you?' },
  { id: 'q044', tags: ['anniversary'], text: "What's one thing the past year taught you?" },
  { id: 'q045', tags: ['person_seen'], text: 'You spent time with {person} yesterday. What did you talk about?' },
  { id: 'q046', tags: ['person_seen'], text: "What's something {person} said recently that stuck with you?" },
  { id: 'q047', tags: ['person_seen'], text: 'What do you and {person} laugh about?' },
  { id: 'q048', tags: ['person_seen'], text: 'What did you and {person} do together this week?' },
  { id: 'q049', tags: ['person_seen'], text: 'How did {person} seem the last time you saw them?' },
  { id: 'q050', tags: ['person_seen'], text: 'What would you like to remember about your time with {person}?' },
  { id: 'q051', tags: ['person_seen'], text: "What's one thing you like about {person}?" },
  { id: 'q052', tags: ['person_seen'], text: 'Where did you and {person} last spend time together?' },
  { id: 'q053', tags: ['person_seen'], text: 'What did {person} teach you, even without meaning to?' },
  { id: 'q054', tags: ['person_seen'], text: "What's a small habit you've noticed in {person}?" },
  { id: 'q055', tags: ['person_seen'], text: 'What would you like to do next with {person}?' },
  { id: 'q056', tags: ['person_seen'], text: 'What did you and {person} eat or drink together?' },
  { id: 'q057', tags: ['person_seen'], text: 'How did you and {person} first meet?' },
  { id: 'q058', tags: ['person_seen'], text: "What's something new you've learned about {person}?" },
  { id: 'q059', tags: ['person_seen'], text: 'What was the best moment with {person} this week?' },
  { id: 'q060', tags: ['person_seen'], text: 'What does a normal day with {person} look like?' },
  { id: 'q061', tags: ['person_seen'], text: 'What would {person} say about your week?' },
  { id: 'q062', tags: ['place_first_time'], text: 'How was your first time at {place} yesterday?' },
  { id: 'q063', tags: ['place_first_time'], text: 'What did you notice first about {place}?' },
  { id: 'q064', tags: ['place_first_time'], text: 'What did {place} sound like?' },
  { id: 'q065', tags: ['place_first_time'], text: 'Who were you with at {place}?' },
  { id: 'q066', tags: ['place_first_time'], text: 'What would you tell someone about {place} before they go?' },
  { id: 'q067', tags: ['place_first_time'], text: 'What was the light like at {place}?' },
  { id: 'q068', tags: ['place_first_time'], text: 'What brought you to {place}?' },
  { id: 'q069', tags: ['place_first_time'], text: 'What would bring you back to {place}?' },
  { id: 'q070', tags: ['place_first_time'], text: 'What surprised you at {place}?' },
  { id: 'q071', tags: ['place_first_time'], text: 'What did {place} smell like?' },
  { id: 'q072', tags: ['place_first_time'], text: "What's a detail from {place} you want to remember?" },
  { id: 'q073', tags: ['weekday'], text: 'What was the best ten minutes of your workday?' },
  { id: 'q074', tags: ['weekday'], text: 'What was the first thing you did after work today?' },
  { id: 'q075', tags: ['weekday'], text: 'Who did you talk to most today?' },
  { id: 'q076', tags: ['weekday'], text: 'What got you through the hardest part of today?' },
  { id: 'q077', tags: ['weekday'], text: 'What did you finish today?' },
  { id: 'q078', tags: ['weekday'], text: 'How did you spend your lunch break today?' },
  { id: 'q079', tags: ['weekday'], text: 'What did you see on your way in today?' },
  { id: 'q080', tags: ['weekday'], text: "What's something you learned today?" },
  { id: 'q081', tags: ['weekday'], text: 'What made today different from yesterday?' },
  { id: 'q082', tags: ['weekday'], text: 'What did you do today that nobody saw?' },
  { id: 'q083', tags: ['weekday'], text: 'What was the view from where you spent most of today?' },
  { id: 'q084', tags: ['weekday'], text: 'Who made your day a little easier?' },
  { id: 'q085', tags: ['weekday'], text: 'What did you look forward to today?' },
  { id: 'q086', tags: ['weekday'], text: 'What would you change about today if you could?' },
  { id: 'q087', tags: ['weekday'], text: 'What song was stuck in your head today?' },
  { id: 'q088', tags: ['weekday'], text: 'What was the busiest moment of your day?' },
  { id: 'q089', tags: ['weekday'], text: 'What did you keep thinking about today?' },
  { id: 'q090', tags: ['weekday'], text: 'What was the quietest moment of your day?' },
  { id: 'q091', tags: ['weekday'], text: 'What did you say yes to today?' },
  { id: 'q092', tags: ['weekday'], text: 'How did your evening start?' },
  { id: 'q093', tags: ['weekday'], text: 'What small choice did you make today that you liked?' },
  { id: 'q094', tags: ['weekend'], text: 'What did this morning sound like?' },
  { id: 'q095', tags: ['weekend'], text: 'What did you do today that you never have time for during the week?' },
  { id: 'q096', tags: ['weekend'], text: 'Who did you spend time with this weekend?' },
  { id: 'q097', tags: ['weekend'], text: 'What was the slowest part of your day?' },
  { id: 'q098', tags: ['weekend'], text: 'Where did you go today, even if it was just round the corner?' },
  { id: 'q099', tags: ['weekend'], text: 'What did you cook or eat today that you enjoyed?' },
  { id: 'q100', tags: ['weekend'], text: 'What did you do today just because you wanted to?' },
  { id: 'q101', tags: ['weekend'], text: 'What are you happy to leave until next week?' },
  { id: 'q102', tags: ['weekend'], text: 'What was the best hour of your day?' },
  { id: 'q103', tags: ['weekend'], text: 'What did you see outside today?' },
  { id: 'q104', tags: ['weekend'], text: 'What did you read, watch or listen to today?' },
  { id: 'q105', tags: ['weekend'], text: 'How did this weekend feel different from last weekend?' },
  { id: 'q106', tags: ['weekend'], text: 'What did you make or fix today?' },
  { id: 'q107', tags: ['weekend'], text: 'What did you do this morning before anything else?' },
  { id: 'q108', tags: ['weekend'], text: 'What made today feel like a day off?' },
  { id: 'q109', tags: ['weekend'], text: "Who did you talk to today that you don't see during the week?" },
  { id: 'q110', tags: ['weekend'], text: "What did you do this weekend that you'd like to keep doing in the week?" },
  { id: 'q111', tags: ['season'], text: 'What have you noticed about the light lately?' },
  { id: 'q112', tags: ['season'], text: 'What does this time of year smell like where you are?' },
  { id: 'q113', tags: ['season'], text: 'What are you wearing more of now than a month ago?' },
  { id: 'q114', tags: ['season'], text: 'How has the weather changed your plans lately?' },
  { id: 'q115', tags: ['season'], text: "What's growing, falling or changing outside right now?" },
  { id: 'q116', tags: ['season'], text: 'What do you look forward to at this time of year?' },
  { id: 'q117', tags: ['season'], text: 'What does the sky look like in the evening now?' },
  { id: 'q118', tags: ['season'], text: 'What food feels right for this time of year?' },
  { id: 'q119', tags: ['season'], text: 'How have your days changed with the season?' },
  { id: 'q120', tags: ['general'], text: 'What made you laugh today?' },
  { id: 'q121', tags: ['general'], text: "What's one thing you want to remember from today?" },
  { id: 'q122', tags: ['general'], text: 'Who did you think about today?' },
  { id: 'q123', tags: ['general'], text: 'What was the best thing you heard today?' },
  { id: 'q124', tags: ['general'], text: 'What did you notice today that you usually walk past?' },
  { id: 'q125', tags: ['general'], text: 'What are you glad about today?' },
  { id: 'q126', tags: ['general'], text: 'What was the most beautiful thing you saw today?' },
  { id: 'q127', tags: ['general'], text: 'What are you looking forward to?' },
  { id: 'q128', tags: ['general'], text: 'What did you do today that felt like you?' },
  { id: 'q129', tags: ['general'], text: 'What surprised you today?' },
  { id: 'q130', tags: ['general'], text: "What's on your mind right now?" },
  { id: 'q131', tags: ['general'], text: 'What was the kindest thing you saw today?' },
  { id: 'q132', tags: ['general'], text: 'What did you learn about yourself today?' },
  { id: 'q133', tags: ['general'], text: 'What made today a bit better?' },
  { id: 'q134', tags: ['general'], text: 'What was the best thing you tasted today?' },
  { id: 'q135', tags: ['general'], text: 'What was the weather like where you were today?' },
  { id: 'q136', tags: ['general'], text: 'Where did you feel most at ease today?' },
  { id: 'q137', tags: ['general'], text: 'What conversation from today would you like to keep?' },
  { id: 'q138', tags: ['general'], text: 'What did you make time for today?' },
  { id: 'q139', tags: ['general'], text: 'If today were a film, what would it be called?' },
  { id: 'q140', tags: ['general'], text: 'What was the soundtrack of your day?' },
  { id: 'q141', tags: ['general'], text: 'What are you curious about right now?' },
  { id: 'q142', tags: ['general'], text: 'What did you stop worrying about today?' },
  { id: 'q143', tags: ['general'], text: 'What did you try for the first time today?' },
  { id: 'q144', tags: ['general'], text: 'Who do you want to thank today?' },
  { id: 'q145', tags: ['general'], text: 'Which part of today would you want to watch years from now?' },
  { id: 'q146', tags: ['general'], text: 'What did you make or do with your hands today?' },
  { id: 'q147', tags: ['general'], text: 'If today had a colour, what would it be?' },
  { id: 'q148', tags: ['general'], text: 'Where were you at sunset today?' },
  { id: 'q149', tags: ['general'], text: 'If you could send yourself a message about today to read in a year, what would it say?' },
  { id: 'q150', tags: ['general'], text: 'What did you hear someone say today that made you think?' },
  { id: 'q151', tags: ['general'], text: 'What felt easy today?' },
];
