import type { QuestionTemplate } from '@life/contracts';

/**
 * The daily question bank (P7). One question per template, answered out loud in about ten seconds.
 * Slot templates ({storyline}, {person}, {place}) carry only their slot's tag. The engine fills slots
 * with names the person typed; it never infers anything about them.
 */
// One template per line so the bank reads as a list.
// prettier-ignore
export const questionTemplates: readonly QuestionTemplate[] = [
  { id: 'q001', tags: ['open_storyline'], text: 'Where are things with {storyline} this week?' },
  { id: 'q002', tags: ['open_storyline'], text: 'What happened next with {storyline}?' },
  { id: 'q003', tags: ['open_storyline'], text: 'What is one small step you took on {storyline} today?' },
  { id: 'q004', tags: ['open_storyline'], text: 'Who else is part of {storyline} right now?' },
  { id: 'q005', tags: ['open_storyline'], text: 'What surprised you about {storyline} lately?' },
  { id: 'q006', tags: ['open_storyline'], text: "If {storyline} were a chapter, what would today's scene be?" },
  { id: 'q007', tags: ['open_storyline'], text: 'What is the hardest part of {storyline} at the moment?' },
  { id: 'q008', tags: ['open_storyline'], text: 'What would you like to remember about {storyline} from this week?' },
  { id: 'q009', tags: ['open_storyline'], text: 'What changed with {storyline} since you last talked about it?' },
  { id: 'q010', tags: ['open_storyline'], text: 'What are you waiting for with {storyline}?' },
  { id: 'q011', tags: ['open_storyline'], text: 'How does {storyline} feel today compared with when it started?' },
  { id: 'q012', tags: ['open_storyline'], text: 'What did you learn from {storyline} this week?' },
  { id: 'q013', tags: ['open_storyline'], text: 'What is going well with {storyline}?' },
  { id: 'q014', tags: ['open_storyline'], text: 'What is one detail from {storyline} that you want on the record?' },
  { id: 'q015', tags: ['open_storyline'], text: 'Where were you when you last thought about {storyline}?' },
  { id: 'q016', tags: ['open_storyline'], text: 'What would you tell a friend about {storyline} today?' },
  { id: 'q017', tags: ['open_storyline'], text: 'What is the next thing that needs to happen for {storyline}?' },
  { id: 'q018', tags: ['open_storyline'], text: 'What sound or image goes with {storyline} today?' },
  { id: 'q019', tags: ['open_storyline'], text: 'Who helped with {storyline} recently?' },
  { id: 'q020', tags: ['open_storyline'], text: 'What made you smile about {storyline} this week?' },
  { id: 'q021', tags: ['open_storyline'], text: 'What question about {storyline} is still open for you?' },
  { id: 'q022', tags: ['open_storyline'], text: 'How did {storyline} show up in your day today?' },
  { id: 'q023', tags: ['after_quiet_days'], text: 'It has been a quiet few days. What is one small thing from today?' },
  { id: 'q024', tags: ['after_quiet_days'], text: 'What has the pace of your days been like lately?' },
  { id: 'q025', tags: ['after_quiet_days'], text: 'What is something ordinary from today that you would like to keep?' },
  { id: 'q026', tags: ['after_quiet_days'], text: 'What did a slow moment look like today?' },
  { id: 'q027', tags: ['after_quiet_days'], text: 'What is one thing you did for yourself today?' },
  { id: 'q028', tags: ['after_quiet_days'], text: 'What was the first thing you noticed when you woke up today?' },
  { id: 'q029', tags: ['after_quiet_days'], text: 'What have you been enjoying quietly this week?' },
  { id: 'q030', tags: ['after_quiet_days'], text: 'What is on your mind as the day winds down?' },
  { id: 'q031', tags: ['after_quiet_days'], text: 'What did you eat today that you liked?' },
  { id: 'q032', tags: ['after_quiet_days'], text: 'Where did you spend most of today?' },
  { id: 'q033', tags: ['after_quiet_days'], text: 'What is one sound you heard today?' },
  { id: 'q034', tags: ['after_quiet_days'], text: 'What small thing went right today?' },
  { id: 'q035', tags: ['after_quiet_days'], text: 'What would you like tomorrow to hold?' },
  { id: 'q036', tags: ['anniversary'], text: 'A year ago today you recorded a moment. What is different about today?' },
  { id: 'q037', tags: ['anniversary'], text: 'A year ago you were in a different season of life. What has changed since?' },
  { id: 'q038', tags: ['anniversary'], text: 'Looking back one year, what would you tell yourself?' },
  { id: 'q039', tags: ['anniversary'], text: 'A year ago today you kept a memory. Who is in your days now?' },
  { id: 'q040', tags: ['anniversary'], text: 'What is something you do now that you did not do a year ago?' },
  { id: 'q041', tags: ['anniversary'], text: 'A year has passed since this day last year. What are you proud of?' },
  { id: 'q042', tags: ['anniversary'], text: 'What from a year ago is still part of your life today?' },
  { id: 'q043', tags: ['anniversary'], text: 'One year on, what does an ordinary day look like for you?' },
  { id: 'q044', tags: ['anniversary'], text: 'What did the past year teach you, in one sentence?' },
  { id: 'q045', tags: ['person_seen'], text: 'You spent time with {person} yesterday. What did you talk about?' },
  { id: 'q046', tags: ['person_seen'], text: 'What is something {person} said recently that stayed with you?' },
  { id: 'q047', tags: ['person_seen'], text: 'What do you and {person} laugh about?' },
  { id: 'q048', tags: ['person_seen'], text: 'What did you and {person} do together this week?' },
  { id: 'q049', tags: ['person_seen'], text: 'How did {person} seem the last time you saw them?' },
  { id: 'q050', tags: ['person_seen'], text: 'What would you like to remember about your time with {person}?' },
  { id: 'q051', tags: ['person_seen'], text: 'What is one thing you appreciate about {person} today?' },
  { id: 'q052', tags: ['person_seen'], text: 'Where were you and {person} when you last met?' },
  { id: 'q053', tags: ['person_seen'], text: 'What did {person} teach you, even without meaning to?' },
  { id: 'q054', tags: ['person_seen'], text: 'What is a small habit of {person} that you notice?' },
  { id: 'q055', tags: ['person_seen'], text: 'What would you like to do next with {person}?' },
  { id: 'q056', tags: ['person_seen'], text: 'What did you and {person} eat or drink together?' },
  { id: 'q057', tags: ['person_seen'], text: 'How did you and {person} meet, in a sentence?' },
  { id: 'q058', tags: ['person_seen'], text: 'What is something new you learned about {person}?' },
  { id: 'q059', tags: ['person_seen'], text: 'What was the best moment with {person} this week?' },
  { id: 'q060', tags: ['person_seen'], text: 'What does a normal day with {person} look like?' },
  { id: 'q061', tags: ['person_seen'], text: 'What would {person} say about your week?' },
  { id: 'q062', tags: ['place_first_time'], text: 'Yesterday you were at {place}. What was it like the first time?' },
  { id: 'q063', tags: ['place_first_time'], text: 'What did you notice first about {place}?' },
  { id: 'q064', tags: ['place_first_time'], text: 'What did {place} sound like?' },
  { id: 'q065', tags: ['place_first_time'], text: 'Who were you with at {place}?' },
  { id: 'q066', tags: ['place_first_time'], text: 'What would you tell someone about {place} before they go?' },
  { id: 'q067', tags: ['place_first_time'], text: 'What was the light like at {place}?' },
  { id: 'q068', tags: ['place_first_time'], text: 'What brought you to {place}?' },
  { id: 'q069', tags: ['place_first_time'], text: 'What would bring you back to {place}?' },
  { id: 'q070', tags: ['place_first_time'], text: 'What surprised you at {place}?' },
  { id: 'q071', tags: ['place_first_time'], text: 'What did {place} smell like?' },
  { id: 'q072', tags: ['place_first_time'], text: 'What is one detail from {place} you want to remember?' },
  { id: 'q073', tags: ['weekday'], text: 'What was the best ten minutes of your workday?' },
  { id: 'q074', tags: ['weekday'], text: 'What was the first thing you did after work today?' },
  { id: 'q075', tags: ['weekday'], text: 'Who did you talk to most today?' },
  { id: 'q076', tags: ['weekday'], text: 'What got you through the hardest part of today?' },
  { id: 'q077', tags: ['weekday'], text: 'What did you finish today?' },
  { id: 'q078', tags: ['weekday'], text: 'What did your lunch break look like today?' },
  { id: 'q079', tags: ['weekday'], text: 'What did you see on the way to where you needed to be?' },
  { id: 'q080', tags: ['weekday'], text: 'What is one thing you learned today?' },
  { id: 'q081', tags: ['weekday'], text: 'What made today different from yesterday?' },
  { id: 'q082', tags: ['weekday'], text: 'What did you do today that nobody saw?' },
  { id: 'q083', tags: ['weekday'], text: 'What was the view from where you spent most of today?' },
  { id: 'q084', tags: ['weekday'], text: 'Who made your day a little easier?' },
  { id: 'q085', tags: ['weekday'], text: 'What did you look forward to today?' },
  { id: 'q086', tags: ['weekday'], text: 'What is one thing you would do differently about today?' },
  { id: 'q087', tags: ['weekday'], text: 'What song or sound was in your head today?' },
  { id: 'q088', tags: ['weekday'], text: 'What was the busiest moment of your day?' },
  { id: 'q089', tags: ['weekday'], text: 'What did you carry with you today?' },
  { id: 'q090', tags: ['weekday'], text: 'What was the quietest moment of your day?' },
  { id: 'q091', tags: ['weekday'], text: 'What did you say yes to today?' },
  { id: 'q092', tags: ['weekday'], text: 'How did your evening begin?' },
  { id: 'q093', tags: ['weekday'], text: 'What small choice did you make today that you liked?' },
  { id: 'q094', tags: ['weekend'], text: 'What did this weekend morning sound like?' },
  { id: 'q095', tags: ['weekend'], text: 'What did you do today that you never have time for during the week?' },
  { id: 'q096', tags: ['weekend'], text: 'Who did you spend time with this weekend?' },
  { id: 'q097', tags: ['weekend'], text: 'What was the slowest part of your day?' },
  { id: 'q098', tags: ['weekend'], text: 'Where did you go today, even if it was close by?' },
  { id: 'q099', tags: ['weekend'], text: 'What did you cook or eat today that you enjoyed?' },
  { id: 'q100', tags: ['weekend'], text: 'What did you do today just because you wanted to?' },
  { id: 'q101', tags: ['weekend'], text: 'What did you put off until next week, happily?' },
  { id: 'q102', tags: ['weekend'], text: 'What was the best hour of today?' },
  { id: 'q103', tags: ['weekend'], text: 'What did you see outside today?' },
  { id: 'q104', tags: ['weekend'], text: 'What did you read, watch or listen to today?' },
  { id: 'q105', tags: ['weekend'], text: 'How did this weekend feel different from last weekend?' },
  { id: 'q106', tags: ['weekend'], text: 'What did you make or fix today?' },
  { id: 'q107', tags: ['weekend'], text: 'What did you do this morning before anything else?' },
  { id: 'q108', tags: ['weekend'], text: 'What made today feel like a day off?' },
  { id: 'q109', tags: ['weekend'], text: 'Who did you talk to today that you do not see during the week?' },
  { id: 'q110', tags: ['weekend'], text: 'What would you like to carry from this weekend into the week?' },
  { id: 'q111', tags: ['season'], text: 'The light changes this time of year. What did you notice today?' },
  { id: 'q112', tags: ['season'], text: 'What does this time of year smell like where you are?' },
  { id: 'q113', tags: ['season'], text: 'What are you wearing more of now than a month ago?' },
  { id: 'q114', tags: ['season'], text: 'How has the weather changed your plans lately?' },
  { id: 'q115', tags: ['season'], text: 'What is growing, falling or changing outside right now?' },
  { id: 'q116', tags: ['season'], text: 'What do you look forward to at this time of year?' },
  { id: 'q117', tags: ['season'], text: 'What does the sky look like in the evening now?' },
  { id: 'q118', tags: ['season'], text: 'What food feels right for this time of year?' },
  { id: 'q119', tags: ['season'], text: 'What has the change in season changed about your days?' },
  { id: 'q120', tags: ['general'], text: 'What made you laugh today?' },
  { id: 'q121', tags: ['general'], text: 'What is one thing you want to remember from today?' },
  { id: 'q122', tags: ['general'], text: 'Who did you think about today?' },
  { id: 'q123', tags: ['general'], text: 'What was the best thing you heard today?' },
  { id: 'q124', tags: ['general'], text: 'What did you notice today that you usually walk past?' },
  { id: 'q125', tags: ['general'], text: 'What are you grateful for today, in one sentence?' },
  { id: 'q126', tags: ['general'], text: 'What was the most beautiful thing you saw today?' },
  { id: 'q127', tags: ['general'], text: 'What is something you are looking forward to?' },
  { id: 'q128', tags: ['general'], text: 'What did you do today that felt like you?' },
  { id: 'q129', tags: ['general'], text: 'What surprised you today?' },
  { id: 'q130', tags: ['general'], text: 'What is on your mind right now?' },
  { id: 'q131', tags: ['general'], text: 'What was the kindest thing you saw today?' },
  { id: 'q132', tags: ['general'], text: 'What did you learn about yourself today?' },
  { id: 'q133', tags: ['general'], text: 'What is a small thing that made today better?' },
  { id: 'q134', tags: ['general'], text: 'What did today taste like?' },
  { id: 'q135', tags: ['general'], text: 'What was the weather like where you were today?' },
  { id: 'q136', tags: ['general'], text: 'Where did you feel most at ease today?' },
  { id: 'q137', tags: ['general'], text: 'What conversation from today would you like to keep?' },
  { id: 'q138', tags: ['general'], text: 'What did you make time for today?' },
  { id: 'q139', tags: ['general'], text: "What would today's title be if it were a film?" },
  { id: 'q140', tags: ['general'], text: 'What was the soundtrack of your day?' },
  { id: 'q141', tags: ['general'], text: 'What are you curious about right now?' },
  { id: 'q142', tags: ['general'], text: 'What did you let go of today?' },
  { id: 'q143', tags: ['general'], text: 'What is something new you tried today?' },
  { id: 'q144', tags: ['general'], text: 'Who would you like to thank for something today?' },
  { id: 'q145', tags: ['general'], text: 'What moment from today would you like to watch on film one day?' },
  { id: 'q146', tags: ['general'], text: 'What did your hands do today?' },
  { id: 'q147', tags: ['general'], text: 'What colour was today?' },
  { id: 'q148', tags: ['general'], text: 'Where were you at sunset today?' },
  { id: 'q149', tags: ['general'], text: 'What is one thing you would tell your future self about today?' },
  { id: 'q150', tags: ['general'], text: 'What did you hear someone say today that made you think?' },
  { id: 'q151', tags: ['general'], text: 'What felt easy today?' },
];
