// The voice rules a test can check (DESIGN §8): phrases that read like stock or machine wording, and
// characters that never appear in UI text. Matched case-insensitively as whole words.
export const voiceBannedPhrases = [
  'at a glance',
  'seamless',
  'seamlessly',
  'effortless',
  'effortlessly',
  'unlock',
  'unlocked',
  'elevate',
  'dive in',
  'dive into',
  'deep dive',
  'delve',
  'journey',
  'embark',
  'tailored',
  'curated',
  'empower',
  'empowering',
  'harness',
  'insights',
  'in just a few taps',
  'a few taps',
  'made easy',
  'your story, your way',
  'cherish',
  'cherished',
  'treasure',
  'treasured',
  'memories that last',
  'lasting memories',
  'precious memories',
  'moments that matter',
  'every moment counts',
  "we've got you",
  'got you covered',
  'oops',
  'whoops',
  'uh oh',
  'something went wrong',
  "let's",
  "here's",
  'great job',
  'good job',
  'well done',
  'nice work',
  'awesome',
  'congrats',
  'congratulations',
  'yay',
  'woohoo',
  'you did it',
  "you've got this",
  'you got this',
  'keep it up',
  "whether you're",
  'not just',
  'more than just',
  "it's not about",
  'game-changer',
  'next level',
  'supercharge',
  'streamline',
  'unleash',
  'leverage',
  'utilise',
  'utilize',
  'revolutionise',
  'revolutionize',
  'reimagine',
  'tapestry',
  'realm',
  'testament',
  'stunning',
  'kindly',
  'feel free to',
  'happy to help',
  'here to help',
  'hope this helps',
  'great question',
  'as an ai',
  'ai-powered',
  'powered by ai',
  'hey there',
  'hi there',
  'take a moment',
  'reflect on',
  'check in with yourself',
  'hold space',
  'safe space',
  'self-care',
  'mindful',
  'mindfulness',
  'be kind to yourself',
  'friendly reminder',
  'gentle reminder',
  'quiet reminder',
  'gentle nudge',
  'try once more',
  'could not',
  'no longer available',
  'on the record',
  'season of life',
  'in one sentence',
  'in a sentence',
  'you missed',
  'you forgot',
  "don't miss",
  "don't forget",
  'finally',
  'in a row',
  'streak',
  'streaks',
  'badge',
  'badges',
  'level up',
  'leaderboard',
  'points',
  'xp',
  'achievement',
  'achievements',
] as const;

export const voiceBannedCharacters = ['!', '—', '–', ';'] as const;
